version: 2.0

jobs:
  info:
    docker:
      - image: najahi/oven:proton
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash .circleci/info

  build:
    docker:
      - image: najahi/oven:proton
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash .circleci/build

workflows:
  version: 2
  build:
    jobs:
      - info
      - build
